name: Consumers

on: [push]

jobs:
  app-mobile:
    name: cremalab/app-mobile
    runs-on: ubuntu-latest
    env:
      CI: true
      SKIP_PREFLIGHT_CHECK: true
    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: 'recursive'
      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      - run: npm ci
      - run: npm run ci:mobile
  app-web:
    name: cremalab/app-web
    runs-on: ubuntu-latest
    env:
      CI: true
      SKIP_PREFLIGHT_CHECK: true
    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: 'recursive'
      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      - run: npm ci
      - run: npm run ci:web