name: Consumers

on: [push]

jobs:
  # app-mobile:
  #   name: cremalab/app-mobile
  #   runs-on: ubuntu-latest
  #   env:
  #     CI: true
  #     SKIP_PREFLIGHT_CHECK: true
  #   steps:
  #     - uses: actions/checkout@v2
  #       with: 
  #         submodules: 'recursive'
  #     - run: npm ci
  #     - run: sudo npm run ci:mobile
  app-web:
    name: cremalab/app-web
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14' ]
    env:
      CI: true
      SKIP_PREFLIGHT_CHECK: true
    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: 'recursive'
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: sudo npm run ci:web