name: Consumers

on: [push]

jobs:

  app-web:
    name: cremalab/app-web
    runs-on: ubuntu-latest
    env:
      CI: true
      SKIP_PREFLIGHT_CHECK: true 

    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: 'recursive'

      - name: Read .nvmrc
        run: echo "::set-output name=NVMRC::$(cat .nvmrc)"
        id: nvm

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - run: npm ci
      - run: sudo npm run ci:web

  app-mobile:
    name: cremalab/app-mobile
    runs-on: ubuntu-latest
    env:
      CI: true
      SKIP_PREFLIGHT_CHECK: true 

    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: 'recursive'
      
      - name: Read .nvmrc
        run: echo "::set-output name=NVMRC::$(cat .nvmrc)"
        id: nvm

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
      
      - run: npm ci
      - run: sudo npm run ci:mobile