name: Consumers

on: [push]

jobs:
  app-mobile:
    name: cremalab/app-mobile
    runs-on: ubuntu-latest
    env:
      CI: true
      SKIP_PREFLIGHT_CHECK: true
    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: 'recursive'
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm i -g npm@6.14.11
      - run: npm ci
      - run: sudo npm run ci:mobile
  app-web:
    name: cremalab/app-web
    runs-on: ubuntu-latest
    env:
      CI: true
      SKIP_PREFLIGHT_CHECK: true
    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: 'recursive'
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm i -g npm@6.14.11
      - run: npm ci
      - run: sudo npm run ci:web