name: Consumers

on: [push]

jobs:
  app-web:
    name: cremalab/app-web
    runs-on: ubuntu-latest
    env:
      CI: true
      SKIP_PREFLIGHT_CHECK: true 

    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: 'recursive'
      - run: npm ci
      # - run: sudo npm run ci:web
  app-mobile:
    name: cremalab/app-mobile
    runs-on: ubuntu-latest
    env:
      CI: true
      SKIP_PREFLIGHT_CHECK: true 

    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: 'recursive'
      - run: npm ci
      - run: sudo npm run ci:mobile