name: Used By

on: [push]

jobs:
  cremalab-app-web:
    name: cremalab/app-web
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - run: npm run bootstrap
      - uses: actions/checkout@v2
        with:
          repository: cremalab/app-web
          path: app-web
          ref: develop
      - run:
          cd packages/scripts-web &&
          npm link
          cd ../../app-web &&
          npm link @cremalab/scripts-web
      - run:
          cd app-web &&
          npm run test:ci