name: Used By

on: [push]

jobs:
  cremalab-app-web:
    name: cremalab/app-web
    runs-on: ubuntu-latest
    env:
      CI: true
      SKIP_PREFLIGHT_CHECK: true 

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - uses: actions/checkout@v2
        with:
          repository: cremalab/app-web
          path: consumers/app-web
          ref: develop-scripts
      - run: 
          cd packages/scripts-web &&
          sudo npm link
      - run: 
          cd consumers/app-web &&
          npm i &&
          sudo npm link @cremalab/scripts-web
      - run: npm run bootstrap
      - run: npm run test:unit