name: Used By

on: [push]

jobs:
  cremalab-app-web:
    name: cremalab/app-web
    runs-on: ubuntu-latest
    env:
      CI: true
      SKIP_PREFLIGHT_CHECK: true 

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - run: sudo npm run test:ci